---
- name: Create a temporary file
  tempfile:
    suffix: .xml
  register: pcmk_config
  check_mode: false
  changed_when: false
  run_once: true

- name: Dump cluster configuration
  shell: cibadmin --query > {{ pcmk_config.path | quote }}
  check_mode: false
  changed_when: false
  ignore_errors: "{{ ansible_check_mode }}"
  register: dump_result
  run_once: true

- name: Install a sample cluster configuration
  copy:
    dest: "{{ pcmk_config.path }}"
    content: <cib />
  when: ansible_check_mode and dump_result.rc != 0
  check_mode: false
  changed_when: false
  run_once: true

- name: Register configuration checksum
  stat:
    path: "{{ pcmk_config.path }}"
    get_attributes: false
    get_checksum: true
    get_mime: false
  register: before
  run_once: true
