---
# Example variable
# primitive:
#   id: nginx-ip
#   class: ocf
#   provider: heartbeat
#   type: IPaddr2
#   options:
#     ip: 10.0.0.1
#   op:
#     - name: monitor
#       interval: 10s

- name: Create primitive {{ primitive.id | default(primitive_id) }}
  xml:
    path: "{{ pcmk_config.path }}"
    xpath: '{{ primitive_parent }}/primitive[@id="{{ primitive.id | default(primitive_id) }}"]'
  check_mode: false

- name: Set {{ primitive.id | default(primitive_id) }} resource agent
  xml:
    path: "{{ pcmk_config.path }}"
    xpath: '{{ primitive_parent }}/primitive[@id="{{ primitive.id | default(primitive_id) }}"]'
    attribute: "{{ attribute }}"
    value: "{{ primitive[attribute] }}"
  loop:
    - class
    - provider
    - type
  loop_control:
    loop_var: attribute
    label: "{{ '{%s: %s}' | format(attribute, primitive[attribute] | default('<unset>')) }}"
  when: attribute in primitive
  check_mode: false

- name: Configure attributes for {{ primitive.id | default(primitive_id) }}
  include_tasks: nvpair.yml
  vars:
    nvpair_parent: >-
      {{ '%(parent)s/primitive[@id="%(id)s"]/%(type)s_attributes[@id="%(id)s-%(type)s_attributes"]'
      | format(parent = primitive_parent, type = 'instance',
      id = primitive.id | default(primitive_id)) }}
    parent_id: "{{ primitive.id | default(primitive_id) }}-instance_attributes"
  with_dict: "{{ primitive.options | default({}) }}"
  loop_control:
    loop_var: nvpair

- name: Configure meta attributes for {{ primitive.id | default(primitive_id) }}
  include_tasks: nvpair.yml
  vars:
    nvpair_parent: >-
      {{ '%(parent)s/primitive[@id="%(id)s"]/%(type)s_attributes[@id="%(id)s-%(type)s_attributes"]'
      | format(parent = primitive_parent, type = 'meta',
      id = primitive.id | default(primitive_id)) }}
    parent_id: "{{ primitive.id | default(primitive_id) }}-meta_attributes"
  with_dict: "{{ primitive.meta | default({}) }}"
  loop_control:
    loop_var: nvpair

- name: Configure operations for {{ primitive.id | default(primitive_id) }}
  include_tasks: op.yml
  vars:
    op_parent: >-
      {{ '%(parent)s/primitive[@id="%(id)s"]/operations'
      | format(parent = primitive_parent, id = primitive.id | default(primitive_id)) }}
    parent_id: "{{ primitive.id | default(primitive_id) }}"
  loop: "{{ primitive.op | default([]) }}"
  loop_control:
    loop_var: op_properties
