---
- include_tasks: pre.yml

- name: Configure simple resource
  include_tasks: primitive.yml
  vars:
    primitive_parent: /cib/configuration/resources
    primitive: "{{ pcmk_resource }}"
  run_once: true

- include_tasks: post.yml
